name: SPX Algo CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y gcc g++ libgomp1 libopenblas-dev

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Dependency vulnerability scan (pip-audit)
        run: |
          pip install pip-audit --quiet
          pip-audit --requirement requirements.txt --strict \
            || { echo "::warning::pip-audit found vulnerabilities — review before live deploy"; true; }

      - name: Run leakage gate
        run: |
          python -m pytest tests/test_no_leakage.py -v --tb=short

      - name: Run full test suite with coverage
        run: |
          python -m pytest --cov=src --cov-report=xml --cov-fail-under=80 \
            --tb=short -q

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage.xml
